#!/usr/bin/env python3
"""DR-001 Amendment 1 support: extract this PDK's Pelgrom AVT coefficients.

Issue #24's sizing pass sets the comparator's input-pair and latch-pair
widths from an OFFSET BUDGET, which needs a number for how much threshold
mismatch a given device area actually buys on this PDK. That number is not
inferred from literature or ported from a sibling repo -- it is read
directly out of this repo's own installed sky130 model library, and then
confirmed empirically by this script.

WHAT THE MODEL LIBRARY SAYS (the primary evidence -- exact, greppable, and
independent of any simulation):

  libs.tech/combined/continuous/models_fet.spice, inside BOTH the
  sky130_fd_pr__nfet_01v8 and sky130_fd_pr__pfet_01v8 subcircuits, the only
  MC_MM_SWITCH (local-mismatch) term is a threshold shift of the form

      delvto = ... + sw_mm_vth0_<device> * mismatch_factor
                     * MC_MM_SWITCH * AGAUSS(0,1.0,1) / sqrt(l*w*mult)

  i.e. the textbook Pelgrom law  sigma_dVth = AVT / sqrt(W*L*mult), with
  l/w in the subcircuit's own micron units and (sky130.lib.spice)
  mismatch_factor = 1. The coefficients, from
  libs.tech/combined/continuous/models_global.spice:

      sw_mm_vth0_sky130_fd_pr__nfet_01v8 = 3.356e-03   ->  AVT_n = 3.356 mV.um
      sw_mm_vth0_sky130_fd_pr__pfet_01v8 = 5.856e-03   ->  AVT_p = 5.856 mV.um

  Note also what is ABSENT: the companion `deltox` line (the beta/current-
  factor mismatch term) is COMMENTED OUT in both subcircuits. On this PDK,
  at these device flavours, local mismatch is threshold mismatch only --
  there is no beta-mismatch term for a sizing argument to trade against.
  That is why the offset budget in design/comparator.sch is written purely
  in terms of AVT/sqrt(W*L) and carries no Vov-dependent beta term.

WHAT THIS SCRIPT ADDS: an independent empirical confirmation that the terms
really are per-instance (not a single global draw shared by every device),
and that the extracted sigma matches the coefficients above at the
geometries design/comparator.sch actually uses.

The trick that makes this cheap: a single ngspice `.op` on a deck holding N
INDEPENDENT instances of the same device. Each X-instance evaluates its own
AGAUSS() draw, so one simulation yields N samples per geometry instead of
needing N separate mismatch-corner runs -- which matters, because loading
the combined sky130 library dominates the cost of a small deck.

Run (from the repository root):

    source sim/env.sh
    python3 spec/dr-001-support/avt_probe.py

Reported sigma is of the BIAS-DEPENDENT operating-point threshold that
ngspice reports for a BSIM4 device (the same quantity DR-001's own
vth_probe.spice reads), not of `delvto` itself, so it is expected to track
the coefficients above closely but not to reproduce them to three digits.
"""

from __future__ import annotations

import os
import re
import statistics
import subprocess
import sys
import tempfile
from pathlib import Path

# Geometries that matter to design/comparator.sch's sizing, plus the
# placeholder DUT's old input-pair geometry (nfet 4/0.5) as a reference
# point against this repo's own already-committed offset record.
GEOMETRIES = [
    ("nfet", 4, 0.5, "placeholder DUT's old input pair (reference point)"),
    ("nfet", 10, 0.5, "design/comparator.sch input pair M_INN/M_INP"),
    ("nfet", 8, 0.5, "design/comparator.sch latch NMOS M_LATN_P/M_LATN_N"),
    ("pfet", 16, 0.5, "design/comparator.sch latch PMOS M_LATP_P/M_LATP_N"),
    ("pfet", 6, 0.5, "design/comparator.sch internal reset PMOS M_RST_DIP/DIN"),
]
N_INSTANCES = 60
CORNER = "tt_mm"  # local-mismatch corner: MC_MM_SWITCH=1
RNDSEED = 17
TEMP_C = 27

# Model-card coefficients this probe confirms (mV.um) -- see module docstring.
AVT_CARD = {"nfet": 3.356, "pfet": 5.856}


def _tag(dev: str, w: float, ell: float) -> str:
    return f"{dev}_{str(w).replace('.', 'p')}_{str(ell).replace('.', 'p')}"


def build_deck(lib_path: str) -> tuple[str, list[tuple[str, int]]]:
    lines = [
        "* DR-001 Amendment 1 support: Pelgrom AVT extraction (issue #24).",
        "* One .op; each X-instance draws its own AGAUSS() local-mismatch term.",
        "* Generated by spec/dr-001-support/avt_probe.py -- see that file.",
        f".temp {TEMP_C}",
        f".lib {lib_path} {CORNER}",
        f".option rndseed={RNDSEED}",
        "Vdd VDD 0 dc 1.8",
        "Vgn GN 0 dc 0.9",
        "Vgp GP 0 dc 0.9",
    ]
    probes: list[tuple[str, int]] = []
    for dev, w, ell, _why in GEOMETRIES:
        tag = _tag(dev, w, ell)
        model = f"sky130_fd_pr__{dev}_01v8"
        for i in range(N_INSTANCES):
            inst = f"XM_{tag}_{i}"
            node = f"D_{tag}_{i}"
            if dev == "nfet":
                lines.append(f"{inst} {node} GN 0 0 {model} L={ell} W={w} nf=1")
            else:
                lines.append(f"{inst} {node} GP VDD VDD {model} L={ell} W={w} nf=1")
            lines.append(f"Vd_{tag}_{i} {node} 0 dc 0.9")
            probes.append((tag, i))
    lines.append(".control")
    lines.append("op")
    for dev, w, ell, _why in GEOMETRIES:
        tag = _tag(dev, w, ell)
        model = f"sky130_fd_pr__{dev}_01v8"
        for i in range(N_INSTANCES):
            lines.append(f"let v_{tag}_{i} = @m.xm_{tag}_{i}.m{model}[vth]")
            lines.append(f"print v_{tag}_{i}")
    lines.append(".endc")
    lines.append(".end")
    return "\n".join(lines) + "\n", probes


def main() -> int:
    pdk_root = os.environ.get("PDK_ROOT")
    pdk = os.environ.get("PDK")
    if not pdk_root or not pdk:
        print("avt_probe: PDK_ROOT/PDK not set -- run 'source sim/env.sh' first", file=sys.stderr)
        return 2
    lib_path = f"{pdk_root}/{pdk}/libs.tech/combined/sky130.lib.spice"

    deck, _probes = build_deck(lib_path)
    with tempfile.TemporaryDirectory(prefix="avt-probe-") as scratch:
        deck_path = Path(scratch) / "avt_probe.spice"
        deck_path.write_text(deck)
        proc = subprocess.run(
            ["ngspice", "-b", str(deck_path)],
            capture_output=True, text=True, cwd=scratch,
        )
    if proc.returncode != 0:
        print(proc.stdout[-4000:], file=sys.stderr)
        print(proc.stderr[-4000:], file=sys.stderr)
        return 1

    samples: dict[str, list[float]] = {}
    for line in proc.stdout.splitlines():
        m = re.match(r"\s*v_(\w+?)_(\d+)\s*=\s*([-\d.eE+]+)\s*$", line)
        if m:
            samples.setdefault(m.group(1), []).append(float(m.group(3)))

    print(f"Pelgrom AVT extraction -- corner {CORNER}, {TEMP_C} C, "
          f"N={N_INSTANCES} independent instances per geometry, rndseed={RNDSEED}")
    print()
    header = (f"{'geometry':22s} {'N':>4s} {'mean Vth':>10s} {'sigma Vth':>10s} "
              f"{'AVT (meas)':>11s} {'AVT (card)':>11s}")
    print(header)
    print("-" * len(header))
    ok = True
    for dev, w, ell, why in GEOMETRIES:
        tag = _tag(dev, w, ell)
        vals = samples.get(tag, [])
        if len(vals) != N_INSTANCES:
            print(f"{tag:22s}  MISSING ({len(vals)} of {N_INSTANCES} samples parsed)")
            ok = False
            continue
        sigma_mv = statistics.stdev(vals) * 1e3
        avt_meas = sigma_mv * (w * ell) ** 0.5
        print(f"{dev} W={w} L={ell}".ljust(22)
              + f" {len(vals):4d} {statistics.fmean(vals) * 1e3:9.2f}m"
              + f" {sigma_mv:9.3f}m {avt_meas:10.3f}u {AVT_CARD[dev]:10.3f}u"
              + f"   <- {why}")
    print()
    print("Units: Vth in mV, AVT in mV.um. 'AVT (card)' is the model library's own")
    print("sw_mm_vth0_* coefficient (see this script's docstring); 'AVT (meas)' is")
    print("sigma * sqrt(W*L) from the draws above. With N=60 the relative standard")
    print("error on an estimated sigma is 1/sqrt(2(N-1)) ~= 9.3%, so agreement is")
    print("expected at the tens-of-percent level, not to three digits.")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
